### ISSUE TITLE
Requesting for view previously ordered Menu

### ISSUE THREAD

**Issue by shirley-prabhu** [Shirley-jeremiah/Mcdonalds-app-developement#4]
Hi Jeremiah,

Kindly add view previous order function. it will help customer who are regular to order easily.

**Comment by Shirley-jeremiah** [comment]
Hi Prabhu,

Thanks for the Request. We will add this Feature in our project.

**Comment by Shirley-jeremiah** [comment]
Hi Prabhu,

added the Functionality. keep Supporting
